SET(CPP_POSIT_INCLUDE_SEARCH_PATHS
    /usr/local/include/cppPosit
)


FIND_PATH(CPP_POSIT_INCLUDE_DIR NAMES posit10.hpp PATHS ${CPP_POSIT_INCLUDE_SEARCH_PATHS})
SET(CPP_POSIT_FOUND ON)

#    Check include files
IF(NOT CPP_POSIT_INCLUDE_DIR)
    SET(CPP_POSIT_FOUND OFF)
    MESSAGE(STATUS "Could not find CPP_POSIT include. Turning CPP_POSIT_FOUND off")
ENDIF()


IF (CPP_POSIT_FOUND)
    add_definitions(-DUSE_CPP_POSIT)
    IF (NOT CPP_POSIT_FIND_QUIETLY)
        MESSAGE(STATUS "Found CPP_POSIT include: ${CPP_POSIT_INCLUDE_DIR}")
    ENDIF (NOT CPP_POSIT_FIND_QUIETLY)
ELSE (CPP_POSIT_FOUND)
    IF (CPP_POSIT_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find CPP_POSIT")
    ENDIF (CPP_POSIT_FIND_REQUIRED)
ENDIF (CPP_POSIT_FOUND)

MARK_AS_ADVANCED(
    CPP_POSIT_INCLUDE_DIR
    CPP_POSIT
)
